import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;
import 'package:pmis/utils/exceptions/api_exceptions.dart';

class CssService {
  static const _baseUrl = 'http://103.180.163.38/api';
  static const Duration _timeoutDuration = Duration(seconds: 30);

  /// Fetch CSS data from the API
  /// Returns list of CSS records on success, throws appropriate exception on failure
  Future<List<Map<String, dynamic>>> getCssData() async {
    try {
      final uri = Uri.parse('$_baseUrl/CSS');

      final response = await http.get(
        uri,
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
        },
      ).timeout(_timeoutDuration);

      return _handleResponse(response);
    } on SocketException {
      throw const NetworkException(
          'No internet connection. Please check your network.');
    } on HttpException {
      throw const NetworkException('Network error occurred. Please try again.');
    } on FormatException {
      throw const ServerException('Invalid response format from server.');
    } catch (e) {
      if (e is ApiException) rethrow;
      throw NetworkException('An unexpected error occurred: ${e.toString()}');
    }
  }

  /// Handle HTTP response and return parsed data
  List<Map<String, dynamic>> _handleResponse(http.Response response) {
    switch (response.statusCode) {
      case 200:
        try {
          final List<dynamic> dataList =
              jsonDecode(response.body) as List<dynamic>;

          // Convert to List<Map<String, dynamic>>
          final List<Map<String, dynamic>> cssData =
              dataList.map((item) => item as Map<String, dynamic>).toList();

          return cssData;
        } catch (e) {
          if (e is FormatException) {
            throw const ServerException('Invalid JSON response from server');
          }
          rethrow;
        }

      case 400:
        final errorMessage = _extractErrorMessage(response.body);
        throw ValidationException(errorMessage);

      case 401:
        throw const AuthException('Authentication required');

      case 403:
        throw const AuthException(
            'Access denied. Please contact administrator');

      case 404:
        throw const NetworkException(
            'CSS service not found. Please try again later');

      case 408:
        throw const TimeoutException('Request timeout. Please try again');

      case 500:
        throw const ServerException(
            'Internal server error. Please try again later');

      case 502:
      case 503:
      case 504:
        throw const ServerException(
            'Service temporarily unavailable. Please try again later');

      default:
        final errorMessage = _extractErrorMessage(response.body);
        throw NetworkException(errorMessage, response.statusCode);
    }
  }

  /// Extract error message from response body
  String _extractErrorMessage(String responseBody) {
    try {
      final Map<String, dynamic> decoded =
          jsonDecode(responseBody) as Map<String, dynamic>;
      return decoded['message'] ?? decoded['error'] ?? 'An error occurred';
    } catch (e) {
      return 'An error occurred while processing the response';
    }
  }

  /// Convert camelCase field names to PascalCase for API
  Map<String, dynamic> _convertToPascalCase(Map<String, dynamic> data) {
    final Map<String, dynamic> converted = {};

    for (final entry in data.entries) {
      // Skip the id field as it's generated by the API
      if (entry.key == 'id') continue;

      String pascalKey = entry.key;

      // Convert specific field names to PascalCase
      switch (entry.key) {
        case 'inspectionDate':
          pascalKey = 'InspectionDate';
          break;
        case 'inspectorName':
          pascalKey = 'InspectorName';
          break;
        case 'inspectorId':
          pascalKey = 'InspectorId';
          break;
        case 'intRegion':
          pascalKey = 'IntRegion';
          break;
        case 'districtId':
          pascalKey = 'DistrictId';
          break;
        case 'facilityName':
          pascalKey = 'FacilityName';
          break;
        case 'facilityStatus':
          pascalKey = 'FacilityStatus';
          break;
        case 'facilityPersonType':
          pascalKey = 'FacilityPersonType';
          break;
        case 'personName':
          pascalKey = 'PersonName';
          break;
        case 'contact':
          pascalKey = 'Contact';
          break;
        case 'qualifications':
          pascalKey = 'Qualifications';
          break;
        case 'categoryOfpremises':
          pascalKey = 'CategoryOfpremises';
          break;
        case 'other_CategoryPremise':
          pascalKey = 'Other_CategoryPremise';
          break;
        case 'licenseStatus':
          pascalKey = 'LicenseStatus';
          break;
        case 'licenseNo':
          pascalKey = 'LicenseNo';
          break;
        case 'unlicensed':
          pascalKey = 'Unlicensed';
          break;
        case 'categoryStatus':
          pascalKey = 'CategoryStatus';
          break;
        case 'premisesCondition':
          pascalKey = 'PremisesCondition';
          break;
        case 'recordKeeping':
          pascalKey = 'RecordKeeping';
          break;
        case 'classofDrugs':
          pascalKey = 'ClassofDrugs';
          break;
        case 'unRegisteredDrug':
          pascalKey = 'UnRegisteredDrug';
          break;
        case 'unRegDrugQty':
          pascalKey = 'UnRegDrugQty';
          break;
        case 'action':
          pascalKey = 'Action';
          break;
        case 'latitude':
          pascalKey = 'Latitude';
          break;
        case 'longitude':
          pascalKey = 'Longitude';
          break;
        default:
          // Keep original key if no conversion needed
          pascalKey = entry.key;
      }

      converted[pascalKey] = entry.value;
    }

    return converted;
  }

  /// Post CSS data to the API
  /// Returns success response on success, throws appropriate exception on failure
  Future<Map<String, dynamic>> postCssData(Map<String, dynamic> cssData) async {
    try {
      final uri = Uri.parse('$_baseUrl/CSS');

      // Convert camelCase to PascalCase for API
      final Map<String, dynamic> apiData = _convertToPascalCase(cssData);
      print('Converted CSS API data: $apiData'); // Debug log

      final response = await http
          .post(
            uri,
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
            },
            body: jsonEncode(apiData),
          )
          .timeout(_timeoutDuration);

      return _handlePostResponse(response);
    } on SocketException {
      throw const NetworkException(
          'No internet connection. Please check your network.');
    } on HttpException {
      throw const NetworkException('Network error occurred. Please try again.');
    } on FormatException {
      throw const ServerException('Invalid response format from server.');
    } catch (e) {
      if (e is ApiException) rethrow;
      throw NetworkException('An unexpected error occurred: ${e.toString()}');
    }
  }

  /// Handle POST response
  Map<String, dynamic> _handlePostResponse(http.Response response) {
    switch (response.statusCode) {
      case 200:
      case 201:
        try {
          if (response.body.isEmpty) {
            return {'success': true, 'message': 'CSS data saved successfully'};
          }

          final Map<String, dynamic> data =
              jsonDecode(response.body) as Map<String, dynamic>;
          return data;
        } catch (e) {
          if (e is FormatException) {
            throw const ServerException('Invalid JSON response from server');
          }
          rethrow;
        }

      case 400:
        final errorMessage = _extractErrorMessage(response.body);
        throw ValidationException(errorMessage);

      case 401:
        throw const AuthException('Authentication required');

      case 403:
        throw const AuthException(
            'Access denied. Please contact administrator');

      case 404:
        throw const NetworkException(
            'CSS service not found. Please try again later');

      case 408:
        throw const TimeoutException('Request timeout. Please try again');

      case 500:
        throw const ServerException(
            'Internal server error. Please try again later');

      case 502:
      case 503:
      case 504:
        throw const ServerException(
            'Service temporarily unavailable. Please try again later');

      default:
        final errorMessage = _extractErrorMessage(response.body);
        throw NetworkException(errorMessage, response.statusCode);
    }
  }
}
