// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFFDvwCscc_8lIqDLnAlMV7PAD-it3si8',
    appId: '1:374168665920:web:3105a06f5a47112d8a44a5',
    messagingSenderId: '374168665920',
    projectId: 'p-electronic',
    authDomain: 'p-electronic.firebaseapp.com',
    databaseURL: 'https://p-electronic-default-rtdb.firebaseio.com',
    storageBucket: 'p-electronic.appspot.com',
    measurementId: 'G-TG5M1QP4JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2I9aNemjJV5x4yyT1CP1xIElarDaxiFw',
    appId: '1:374168665920:android:b813200d0cabb9008a44a5',
    messagingSenderId: '374168665920',
    projectId: 'p-electronic',
    databaseURL: 'https://p-electronic-default-rtdb.firebaseio.com',
    storageBucket: 'p-electronic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtLtD8zByol1M6XynMviK9_3txvWq_rIw',
    appId: '1:374168665920:ios:4a50dbfc238a7daf8a44a5',
    messagingSenderId: '374168665920',
    projectId: 'p-electronic',
    databaseURL: 'https://p-electronic-default-rtdb.firebaseio.com',
    storageBucket: 'p-electronic.appspot.com',
    androidClientId: '374168665920-2af6grmj13jrmoj82jbkp078hcsakg3m.apps.googleusercontent.com',
    iosClientId: '374168665920-chc4prgllpftifrd5uk48ef2imoitoa6.apps.googleusercontent.com',
    iosBundleId: 'com.zachsoft.pElectronic',
  );

}